INSERT INTO box(ref, ub) VALUES('H001', 'E1');
INSERT INTO box(ref, ub) VALUES('H002', 'E1');
INSERT INTO box(ref, ub) VALUES('H003', 'E2');

INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego GRID Autosport', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Los 4 Fantásticos y silver surfer', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Fable III', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'DELL Inspiron', 'Ratón', 'negro', null, 2);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'Ferrari 465GT', 'coche escala 1/39', 'gris', null, 3);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego GRID Autosport', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Los 4 Fantásticos y silver surfer', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Fable III', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'DELL Inspiron', 'Ratón', 'negro', null, 2);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Fable III', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'DELL Inspiron', 'Ratón', 'negro', null, 2);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'Ferrari 465GT', 'coche escala 1/39', 'gris', null, 3);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego GRID Autosport', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Los 4 Fantásticos y silver surfer', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'Ferrari 465GT', 'coche escala 1/39', 'gris', null, 3);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego GRID Autosport', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Los 4 Fantásticos y silver surfer', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Fable III', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'DELL Inspiron', 'Ratón', 'negro', null, 2);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego GRID Autosport', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Los 4 Fantásticos y silver surfer', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Fable III', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'Ferrari 465GT', 'coche escala 1/39', 'gris', null, 3);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego GRID Autosport', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Los 4 Fantásticos y silver surfer', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Fable III', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'DELL Inspiron', 'Ratón', 'negro', null, 2);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'Ferrari 465GT', 'coche escala 1/39', 'gris', null, 3);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego GRID Autosport', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Los 4 Fantásticos y silver surfer', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'XBOX 360', 'Juego Fable III', null, null, 1);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'DELL Inspiron', 'Ratón', 'negro', null, 2);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'Ferrari 465GT', 'coche escala 1/39', 'gris', null, 3);
INSERT INTO item(amount, brand, name, color, description, box_id) VALUES(1, 'Ferrari 465GT', 'coche escala 1/39', 'gris', null, 3);